name: HoFaye
favicon: null
layout_spectrum: 0.89574
typography_spectrum: 0.82593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2770265410654247
  lightness: 0.06520839012227952
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
