typography_spectrum: 0.53576
content_rating:
  adult: false
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2770265410654247
  lightness: 0.06520839012227952
  saturation: 0.125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89574
analytics:
  google: null
  facebook: null
  twitter: null
name: HoFaye
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7cf2edf3-9858-4c67-977b-05d56f6003f0.jpg
title: HoFaye
purpose: []
